# Generated by Django 5.0.3 on 2024-03-23 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wname', models.CharField(max_length=255)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branch_app.branch')),
            ],
            options={
                'db_table': 'tbl_worker',
            },
        ),
    ]
