# Generated by Django 5.0.3 on 2024-04-07 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Torol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tbl_torol',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=255)),
                ('bcontent', models.CharField(max_length=2500)),
                ('bdate', models.DateField(auto_now_add=True)),
                ('btorol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_blog.torol')),
            ],
            options={
                'db_table': 'tbl_blog',
            },
        ),
    ]
