# Generated by Django 5.0.3 on 2024-03-12 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('bname', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_branch',
            },
        ),
    ]
