# Generated by Django 5.0.3 on 2024-04-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_app', '0002_queueitem_delete_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='QueueItem',
        ),
    ]
