# Generated by Django 5.0.3 on 2024-03-29 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='nchoose',
            field=models.CharField(choices=[('man', 'Эр'), ('woman', 'Эм')], default='none', max_length=5),
        ),
    ]
