# Generated by Django 5.0.3 on 2024-03-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0002_news_birth_date_news_nchoose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='nchoose',
            field=models.CharField(choices=[('man', 'Эр'), ('woman', 'Эм')], default='', max_length=5),
        ),
    ]
