# Generated by Django 5.0.4 on 2024-11-29 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stlname', models.CharField(max_length=100)),
                ('stfname', models.CharField(max_length=100)),
                ('stcode', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=250)),
                ('born', models.DateTimeField()),
                ('email', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=8)),
                ('username', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
